export const OKRUG_ORDER = ['czao', 'sao', 'svao', 'vao', 'uvao', 'yuao', 'yuzsao', 'zao', 'szao', 'zelenogradskij']

export const OKRUGS = {
  czao:           { name: 'Центральный АО',        short: 'ЦАО' },
  sao:            { name: 'Северный АО',            short: 'САО' },
  svao:           { name: 'Северо-Восточный АО',    short: 'СВАО' },
  vao:            { name: 'Восточный АО',           short: 'ВАО' },
  uvao:           { name: 'Юго-Восточный АО',       short: 'ЮВАО' },
  yuao:           { name: 'Южный АО',               short: 'ЮАО' },
  yuzsao:         { name: 'Юго-Западный АО',        short: 'ЮЗАО' },
  zao:            { name: 'Западный АО',            short: 'ЗАО' },
  szao:           { name: 'Северо-Западный АО',     short: 'СЗАО' },
  zelenogradskij: { name: 'Зеленоградский АО',      short: 'ЗелАО' },
}

export const DISTRICTS = {
  czao: [
    { name: 'Хамовники',           slug: 'hamovniki' },
    { name: 'Арбат',               slug: 'arbat' },
    { name: 'Замоскворечье',       slug: 'zamoskvoreche' },
    { name: 'Красносельский',      slug: 'krasnoselskij' },
    { name: 'Мещанский',           slug: 'meshhanskij' },
    { name: 'Пресненский',         slug: 'presnenskij' },
    { name: 'Таганский',           slug: 'taganskij' },
    { name: 'Тверской',            slug: 'tverskoj' },
    { name: 'Якиманка',            slug: 'yakimanka' },
    { name: 'Басманный',           slug: 'basmannyj' },
    { name: 'Ивановское (ЦАО)',    slug: 'ivanovskoe-czao' },
  ],
  sao: [
    { name: 'Бескудниковский',     slug: 'beskudnikovskij' },
    { name: 'Войковский',          slug: 'vojkovskij' },
    { name: 'Головинский',         slug: 'golovinskij' },
    { name: 'Дегунино Восточное',  slug: 'degunino-vostochnoe' },
    { name: 'Дегунино Западное',   slug: 'degunino-zapadnoe' },
    { name: 'Дмитровский',         slug: 'dmitrovskij' },
    { name: 'Коптево',             slug: 'koptevo' },
    { name: 'Левобережный',        slug: 'levoberezhnij' },
    { name: 'Молжаниновский',      slug: 'molzhaninovskij' },
    { name: 'Савёловский',         slug: 'savelovskij' },
    { name: 'Тимирязевский',       slug: 'timiryazevskij' },
    { name: 'Ховрино',             slug: 'hovrino' },
    { name: 'Химки (Левобережный)',slug: 'himki-levoberezhnij' },
    { name: 'Аэропорт',            slug: 'aehroport' },
    { name: 'Беговой',             slug: 'begovoj' },
  ],
  svao: [
    { name: 'Алексеевский',        slug: 'alekseevskij' },
    { name: 'Алтуфьевский',        slug: 'altufevskij' },
    { name: 'Бабушкинский',        slug: 'babushkinskij' },
    { name: 'Богородское',         slug: 'bogorodskoe' },
    { name: 'Бутырский',           slug: 'butyrskij' },
    { name: 'Лосиноостровский',    slug: 'losinoostrovskij' },
    { name: 'Марфино',             slug: 'marfino' },
    { name: 'Марьина Роща',        slug: 'marina-roshha' },
    { name: 'Медведково Северное', slug: 'medvedkovo-severnoe' },
    { name: 'Медведково Южное',    slug: 'medvedkovo-yuzhnoe' },
    { name: 'Останкинский',        slug: 'ostankinskij' },
    { name: 'Отрадное',            slug: 'otradnoe' },
    { name: 'Ростокино',           slug: 'rostokino' },
    { name: 'Свиблово',            slug: 'sviblovo' },
    { name: 'Северный',            slug: 'severnyj' },
    { name: 'Ярославский',         slug: 'yaroslavskij' },
  ],
  vao: [
    { name: 'Вешняки',             slug: 'veshnyaki' },
    { name: 'Восточное Измайлово', slug: 'vostochnoe-izmajlovo' },
    { name: 'Восточный',           slug: 'vostochnyj' },
    { name: 'Гольяново',           slug: 'golyanov' },
    { name: 'Ивановское',          slug: 'ivanovskoe' },
    { name: 'Измайлово',           slug: 'izmajlovo' },
    { name: 'Косино-Ухтомский',    slug: 'kosino-uhtomskij' },
    { name: 'Метрогородок',        slug: 'metrogorodok' },
    { name: 'Новогиреево',         slug: 'novogireevo' },
    { name: 'Новокосино',          slug: 'novokosino' },
    { name: 'Перово',              slug: 'perovo' },
    { name: 'Преображенское',      slug: 'preobrazhenskoe' },
    { name: 'Северное Измайлово',  slug: 'severnoe-izmajlovo' },
    { name: 'Соколиная Гора',      slug: 'sokolinaya-gora' },
    { name: 'Сокольники',          slug: 'sokolniki' },
  ],
  uvao: [
    { name: 'Выхино-Жулебино',     slug: 'vyhino-zhulebino' },
    { name: 'Жулебино',            slug: 'zhulebino' },
    { name: 'Капотня',             slug: 'kapotnya' },
    { name: 'Кузьминки',           slug: 'kuzminki' },
    { name: 'Лефортово',           slug: 'lefortovo' },
    { name: 'Люблино',             slug: 'lyublino' },
    { name: 'Марьино',             slug: 'marino' },
    { name: 'Некрасовка',          slug: 'nekrasovka' },
    { name: 'Нижегородский',       slug: 'nizhegorodskij' },
    { name: 'Печатники',           slug: 'pechatniki' },
    { name: 'Рязанский',           slug: 'ryazanskij' },
    { name: 'Текстильщики',        slug: 'tekstilshhiki' },
    { name: 'Южнопортовый',        slug: 'yuzhnoportovyj' },
  ],
  yuao: [
    { name: 'Бирюлёво Восточное',          slug: 'biryulevo-vostochnoe' },
    { name: 'Бирюлёво Западное',           slug: 'biryulevo-zapadnoe' },
    { name: 'Братеево',                    slug: 'brateevo' },
    { name: 'Даниловский',                 slug: 'danilovskij' },
    { name: 'Зябликово',                   slug: 'zyablikovo' },
    { name: 'Москворечье-Сабурово',        slug: 'moskvorechye-saburovo' },
    { name: 'Нагатино-Садовники',          slug: 'nagatino-sadovniki' },
    { name: 'Нагатинский Затон',           slug: 'nagatinskij-zaton' },
    { name: 'Нагорный',                    slug: 'nagornyj' },
    { name: 'Орехово-Борисово Северное',   slug: 'orekhovo-borisovo-severnoe' },
    { name: 'Орехово-Борисово Южное',      slug: 'orekhovo-borisovo-yuzhnoe' },
    { name: 'Царицыно',                    slug: 'czaricyno' },
    { name: 'Чертаново Северное',          slug: 'chertanovo-severnoe' },
    { name: 'Чертаново Центральное',       slug: 'chertanovo-czentralnoe' },
    { name: 'Чертаново Южное',             slug: 'chertanovo-yuzhnoe' },
  ],
  yuzsao: [
    { name: 'Бутово',              slug: 'butovo' },
    { name: 'Гагаринский',         slug: 'gagarinskij' },
    { name: 'Зюзино',              slug: 'zyuzino' },
    { name: 'Коньково',            slug: 'konkovo' },
    { name: 'Котловка',            slug: 'kotlovka' },
    { name: 'Ломоносовский',       slug: 'lomonosovskij' },
    { name: 'Обручевский',         slug: 'obruchevskij' },
    { name: 'Северное Бутово',     slug: 'severnoe-butovo' },
    { name: 'Тёплый Стан',         slug: 'tyoplyj-stan' },
    { name: 'Черёмушки',           slug: 'cheremushki' },
    { name: 'Южное Бутово',        slug: 'yuzhnoe-butovo' },
    { name: 'Ясенево',             slug: 'yasenevo' },
  ],
  zao: [
    { name: 'Внуково',             slug: 'vnukovo' },
    { name: 'Дорогомилово',        slug: 'dorogomilovo' },
    { name: 'Крылатское',          slug: 'krylatskoe' },
    { name: 'Кунцево',             slug: 'kunczevo' },
    { name: 'Можайский',           slug: 'mozhajskij' },
    { name: 'Ново-Переделкино',    slug: 'novo-peredelkino' },
    { name: 'Очаково-Матвеевское', slug: 'ochakovo-matveevskoe' },
    { name: 'Проспект Вернадского',slug: 'prospekt-vernadskogo' },
    { name: 'Раменки',             slug: 'ramenki' },
    { name: 'Солнцево',            slug: 'solncevo' },
    { name: 'Тропарёво-Никулино',  slug: 'troparevo-nikulino' },
    { name: 'Фили-Давыдково',      slug: 'fili-davydkovo' },
    { name: 'Филёвский Парк',      slug: 'filevskij-park' },
  ],
  szao: [
    { name: 'Академический',       slug: 'akademicheskij' },
    { name: 'Алтуфьево',           slug: 'altufevo' },
    { name: 'Куркино',             slug: 'kurkino' },
    { name: 'Митино',              slug: 'mitino' },
    { name: 'Покровское-Стрешнево',slug: 'pokrovskoe-streshnevo' },
    { name: 'Северное Тушино',     slug: 'severnoe-tushino' },
    { name: 'Строгино',            slug: 'strogino' },
    { name: 'Хорошёво-Мнёвники',   slug: 'horoshevo-mnevniki' },
    { name: 'Щукино',              slug: 'shhukino' },
    { name: 'Южное Тушино',        slug: 'yuzhnoe-tushino' },
  ],
  zelenogradskij: [
    { name: 'Крюково',             slug: 'kryukovo' },
    { name: 'Матушкино',           slug: 'matushkino' },
    { name: 'Савёлки',             slug: 'savelki' },
    { name: 'Силино',              slug: 'silino' },
    { name: 'Старое Крюково',      slug: 'staroe-kryukovo' },
  ],
}
